package com.ipterebi.core

import java.io.Reader
import java.io.StringReader
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNull
import kotlin.test.assertTrue

/** Reading a line's whole schedule, as panels actually send it. */
class XmltvTest {

    private fun read(xml: String): Pair<List<XmltvChannel>, List<XmltvProgramme>> {
        val channels = mutableListOf<XmltvChannel>()
        val programmes = mutableListOf<XmltvProgramme>()
        readXmltv(StringReader(xml), channels::add, programmes::add)
        return channels to programmes
    }

    private val sample = """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE tv SYSTEM "xmltv.dtd" [ <!ENTITY nbsp "&#160;"> ]>
        <!-- generated by a panel -->
        <tv generator-info-name="panel">
          <channel id="skysports.uk">
            <display-name>Sky Sports Main Event</display-name>
            <display-name>SSME</display-name>
            <icon src="http://example/logo.png"/>
          </channel>
          <programme start="20260912170000 +0000" stop="20260912200000 +0000" channel="skysports.uk">
            <title lang="en">Saturday Night Football</title>
            <title lang="de">Samstagabend-Fußball</title>
            <desc lang="en">Spurs &amp; Everton &#8212; live</desc>
          </programme>
          <programme start="20260912200000 +0000" stop="20260912230000 +0000" channel="skysports.uk">
            <title><![CDATA[US Open <2026>]]></title>
          </programme>
        </tv>
    """.trimIndent()

    @Test
    fun `channels and programmes come out with their first title and decoded text`() {
        val (channels, programmes) = read(sample)
        assertEquals(listOf(XmltvChannel("skysports.uk", "Sky Sports Main Event", "http://example/logo.png")), channels)
        assertEquals(2, programmes.size)
        val match = programmes[0]
        assertEquals("skysports.uk", match.channel)
        assertEquals("Saturday Night Football", match.title)
        assertEquals("Spurs & Everton — live", match.description)
        assertEquals(parseXmltvTime("20260912170000 +0000"), match.start)
        assertEquals(3 * 3600L, match.stop - match.start)
        assertEquals("US Open <2026>", programmes[1].title)
        assertEquals("", programmes[1].description)
    }

    @Test
    fun `a programme with unreadable times or no channel is skipped, not fatal`() {
        val (_, programmes) = read(
            """
            <tv>
              <programme start="nonsense" stop="20260912200000 +0000" channel="a"><title>Bad start</title></programme>
              <programme start="20260912200000 +0000" stop="20260912190000 +0000" channel="a"><title>Ends first</title></programme>
              <programme start="20260912200000 +0000" stop="20260912210000 +0000"><title>No channel</title></programme>
              <programme start="20260912200000 +0000" stop="20260912210000 +0000" channel="a"><title>Fine</title></programme>
            </tv>
            """.trimIndent()
        )
        assertEquals(listOf("Fine"), programmes.map { it.title })
    }

    @Test
    fun `a web page where the guide should be says so`() {
        val e = assertFailsWith<XtreamException> { read("<!DOCTYPE html><html><body>Suspended</body></html>") }
        assertTrue("html" in e.message.orEmpty())
    }

    @Test
    fun `an empty answer says so`() {
        assertFailsWith<XtreamException> { read("   ") }
    }

    @Test
    fun `attributes in single quotes, unquoted, and with entities are read`() {
        val (_, programmes) = read(
            "<tv><programme start='20260912200000 +0000' stop=20260912210000 channel=\"a&amp;b\"><title>X</title></programme></tv>"
        )
        assertEquals("a&b", programmes.single().channel)
    }

    @Test
    fun `a document split across many small reads parses the same`() {
        // The download arrives in pieces; a marker split across two of them
        // must not be lost.
        val trickle = object : Reader() {
            private val source = StringReader(sample)
            override fun read(cbuf: CharArray, off: Int, len: Int) = source.read(cbuf, off, minOf(len, 3))
            override fun close() = source.close()
        }
        val programmes = mutableListOf<XmltvProgramme>()
        readXmltv(trickle, onProgramme = programmes::add)
        assertEquals(read(sample).second, programmes)
    }

    @Test
    fun `times take their own offset`() {
        val utc = parseXmltvTime("20260912170000 +0000")!!
        assertEquals(utc, parseXmltvTime("20260912180000 +0100"))
        assertEquals(utc, parseXmltvTime("20260912180000 +01:00"))
        assertEquals(utc, parseXmltvTime("20260912120000 -0500"))
        assertEquals(utc, parseXmltvTime("202609121700 +0000"))
    }

    @Test
    fun `a time with no offset is taken as UTC`() {
        assertEquals(parseXmltvTime("20260912170000 +0000"), parseXmltvTime("20260912170000"))
    }

    @Test
    fun `unreadable times are null`() {
        assertNull(parseXmltvTime(""))
        assertNull(parseXmltvTime("2026-09-12 17:00"))
        assertNull(parseXmltvTime("20261399170000 +0000"))
        assertNull(parseXmltvTime("20260912170000 GMT"))
    }

    @Test
    fun `entities are decoded and unknown ones left alone`() {
        assertEquals("a & b < c é é &nbsp; &", decodeEntities("a &amp; b &lt; c &#233; &#xE9; &nbsp; &"))
    }
}
